fix(qq): remove `timestamp` in type `Request`
satorijs/satori pull request #208
Opened 2023-12-20 12:50 UTC by ilharp

2023-12-20 16:21 UTC, shigma requested changes
删了类型不考虑同时把实现传进去的删掉吗？

2023-12-20 16:21 UTC, shigma commented
cc @XxLittleCxX

2023-12-21 15:31 UTC, XxLittleCxX commented
旧版文档有说发群消息要 `timestamp`，刚试了下不传也能发，你把实现也删一下吧

2023-12-21 15:34 UTC, ilharp commented
eb7c4407cc7c8a7c67b883bf0d29c16a5baea7da

2023-12-21 16:28 UTC, shigma approved these changes

2023-12-21 16:29 UTC, merged