https://github.com/koishijs/koishi/issues/965
satorijs/satori pull request #76
Opened 2023-02-26 17:35 UTC by Willyoucallme

1. 修改QQ频道不能发图片
2. 修复QQ频道不能私信

2023-02-26 18:06 UTC, shigma reviewed
看起来不错。请问这里还需要上游做哪些配套改动吗？

2023-02-26 18:06 UTC, shigma commented on adapters/qqguild/src/message.ts
> +          data: url.slice(8),
这里能补一个注释说明为什么是 8 的话我会非常感激。

2023-02-26 18:06 UTC, shigma commented on adapters/qqguild/src/bot.ts
> +    if(msg.isPrivate) {
```suggestion
    if (msg.isPrivate) {
```

2023-02-26 18:42 UTC, Willyoucallme commented on adapters/qqguild/src/message.ts
> +          data: url.slice(8),
已补，需要先合并https://github.com/satorijs/qq-guild-sdk/pull/7

2023-02-26 18:48 UTC, shigma commented on adapters/qqguild/src/message.ts
> +          data: url.slice(8),
建议使用 url.fileURLToPath，不然在 posix 系统上你这样做可能得不到绝对路径。

2023-02-27 01:53 UTC, NWYLZW commented on adapters/qqguild/src/message.ts
> +          data: url.slice(8),
该代码只适配 windows，我抽空做一下调整

2023-02-27 03:10 UTC, NWYLZW requested changes

2023-02-27 03:10 UTC, NWYLZW commented on adapters/qqguild/src/bot.ts
> +      session.guildId = ''
为什么这里需要逆转属性，感觉不太对？

2023-02-27 05:01 UTC, NWYLZW commented on adapters/qqguild/src/message.ts
> +        result = await sender.private(this.session.channelId, req)
这里需要上游 sdk 支持，此处代码是不可用的

消息发送需要指定对应的频道以及用户，否则无法创建 dms

2023-02-27 05:03 UTC, Willyoucallme commented on adapters/qqguild/src/message.ts
> +        result = await sender.private(this.session.channelId, req)
有guildID就行了，你的sdk已经处理了

2023-02-27 05:04 UTC, Willyoucallme commented on adapters/qqguild/src/bot.ts
> +      session.guildId = ''
因为如果带有guildId，那么发送session的subtype就会是group
不会进入到这段代码
![image](https://user-images.githubusercontent.com/40047545/221478652-8c1a0dfb-51a0-4b06-a0f4-ed98e540a4a0.png)

把guildId置空后就可正常执行了

2023-02-27 05:17 UTC, NWYLZW commented on adapters/qqguild/src/bot.ts
> +      session.guildId = ''
在上面已经指定了 subtype 的值，按道理来说应该会进入该段逻辑

之前不能进入该段逻辑应该是没有设置 private 出现的

2023-02-27 05:19 UTC, NWYLZW commented on adapters/qqguild/src/bot.ts
> +      session.guildId = ''
@shigma 
这个是 satori 目的行为吗
`如果带有 guildId ，那么发送 session 的 subtype 就会是 group`

2023-02-27 05:20 UTC, Willyoucallme commented on adapters/qqguild/src/bot.ts
> +      session.guildId = ''
> @shigma 这个是 satori 目的行为吗 `如果带有 guildId ，那么发送 session 的 subtype 就会是 group`

是的 我咨询了群主，有guildid的就一定是group

2023-02-27 05:23 UTC, NWYLZW commented on adapters/qqguild/src/message.ts
> +        result = await sender.private(this.session.channelId, req)
是的，但是如我们在 https://github.com/koishijs/koishi/issues/965#issuecomment-1445719511 说的

这个地方创建 dms 会话是需要 uid 的
同时这里使用 channelId 的名字也具备一定的阅读障碍

先看看 guildId 导致判定为 group 的逻辑是否正确，最好把这个换回 guildId
如果没办法，那么也应该加一个注释，防止后面维护造成误解

2023-02-27 05:28 UTC, NWYLZW commented on adapters/qqguild/src/bot.ts
> +      session.guildId = ''
> > @shigma 这个是 satori 目的行为吗 `如果带有 guildId ，那么发送 session 的 subtype 就会是 group`
> 
> 是的 我咨询了群主，有guildid的就一定是group

大致过了一下源码，我没发现没有这部分逻辑（指存在 guildId 就主动修改 message subType 的行为）

2023-02-27 09:11 UTC, shigma commented on adapters/qqguild/src/bot.ts
> +      session.guildId = ''
这个逻辑可以修复，是 satori 的行为：

https://github.com/satorijs/satori/blob/fbcf4665c77381ff80c8718106d2282a931d5736/packages/core/src/message.ts#L23

2023-02-27 09:17 UTC, NWYLZW commented on adapters/qqguild/src/bot.ts
> +      session.guildId = ''
> 这个逻辑可以修复，是 satori 的行为：
> 
> https://github.com/satorijs/satori/blob/fbcf4665c77381ff80c8718106d2282a931d5736/packages/core/src/message.ts#L23

原来如此，就算在 adapter 中补充了 subtype 也会默认采取这个值吗
感觉是有一点问题，我翻阅了一下几个 adapter，都是自行赋值的 subtype

https://github.com/satorijs/satori/blob/fbcf4665c77381ff80c8718106d2282a931d5736/adapters/kook/src/utils.ts#L109
https://github.com/satorijs/satori/blob/fbcf4665c77381ff80c8718106d2282a931d5736/adapters/kook/src/utils.ts#L112
https://github.com/satorijs/satori/blob/fbcf4665c77381ff80c8718106d2282a931d5736/adapters/onebot/src/utils.ts#L188
https://github.com/satorijs/satori/blob/fbcf4665c77381ff80c8718106d2282a931d5736/adapters/discord/src/utils.ts#L132
https://github.com/satorijs/satori/blob/fbcf4665c77381ff80c8718106d2282a931d5736/adapters/telegram/src/bot.ts#L163-L167
https://github.com/satorijs/satori/blob/fbcf4665c77381ff80c8718106d2282a931d5736/adapters/feishu/src/utils.ts#L88

2023-02-27 09:19 UTC, shigma commented on adapters/qqguild/src/bot.ts
> +      session.guildId = ''
你贴出的代码都是接收行为，接收是没问题的。出现问题的部分在发送。

2023-02-27 09:26 UTC, shigma commented on adapters/qqguild/src/bot.ts
> +      session.guildId = ''
这个问题比较麻烦的点在于，目前的 send 是四个参数：channelId content guildId options，但现在这四个参数无法区别 subtype 了。那如果不 breaking 的话就只能在 options 后面补上第五个参数。

一种比较理想的改法是这样：

```ts
bot.sendMessage(sessionLike, content, options?)
```

当有 session 的时候直接传 session 本身（channelId、guildId、subtype）都能拿到；没有 session 的时候就传带这三个属性的对象。但这样改就破坏了已有的行为。

另一种思路是同时兼容两种写法，但是这个兼容是需要 adapter 完成的，等于每个 adapter 都得抄一遍重载逻辑，而且只要用户不更新，下游插件用了新特性照样会导致报错。

2023-02-27 09:32 UTC, NWYLZW commented on adapters/qqguild/src/bot.ts
> +      session.guildId = ''
会 break 我能理解了，不过目前的行为确实有点问题，可以不改，但是我觉得可以优化这一个 case
（指用 channelId 判定是否私聊的行为，感觉不是很好的行为）

2023-02-27 09:33 UTC, shigma commented on adapters/qqguild/src/bot.ts
> +      session.guildId = ''
急用的话可以先短暂支持一下那个五参数的 API。之后 Koishi 4.12 再改掉。

2023-02-27 09:35 UTC, NWYLZW commented on adapters/qqguild/src/bot.ts
> +      session.guildId = ''
> 急用的话可以先短暂支持一下那个五参数的 API。之后 Koishi 4.12 再改掉。

目前不急用，只是代码留在那里比较迷惑，会自己不知道为什么这么写了
（我留一个 TODO 在那里，你如果要做 break 的时候可以一起改了）

这个 pr 我要基于它再改写一下，还是有一些问题的

2023-03-27 02:26 UTC, shigma commented
superseded by #79

2023-03-27 02:26 UTC, closed without merging