feat(telegram): improve browser compatibility
satorijs/satori pull request #78
Opened 2023-02-28 03:50 UTC by shigma

移除了与 node 耦合的部分以获得在浏览器加载的能力。

关于文件上传的部分不太确定写的对不对。

2023-02-28 15:22 UTC, Anillc requested changes

2023-02-28 15:22 UTC, Anillc commented on adapters/telegram/src/message.ts
> +  const { filename, data, mime } = await this.bot.ctx.http.file(element.attrs.url)
这里没有 `this`

2023-02-28 15:22 UTC, Anillc commented on adapters/telegram/src/bot.ts
> +      return await this.file.file(`/${filePath}`)
这里有问题，`ctx.http.file` 并不会考虑 `endpoint`，一个不完整的链接被传入了 `ctx.http.file` 内 `new URL(url)` 导致抛出异常。

2023-02-28 17:20 UTC, shigma commented on adapters/telegram/src/bot.ts
> +      return await this.file.file(`/${filePath}`)
你会建议在 cordis-axios 侧修改这个行为吗？

2023-02-28 17:23 UTC, shigma commented on adapters/telegram/src/bot.ts
> +      return await this.file.file(`/${filePath}`)
我看了一下，其他适配器均有使用此 API，不适合在上游修改，故这里改为字符串拼接。

2023-02-28 17:39 UTC, Anillc commented on adapters/telegram/src/bot.ts
> +      return await this.file.file(`/${filePath}`)
还是有问题...

https://github.com/satorijs/satori/blob/f8a2a6f4fcd8b5b485f56f624919d8c55395be31/packages/axios/src/index.ts#L85

即使这里传入了一个完整的 URI, `this.axios` 仍然会往 url 上加上 endpoint

https://github.com/satorijs/satori/blob/f8a2a6f4fcd8b5b485f56f624919d8c55395be31/packages/axios/src/index.ts#L119

2023-02-28 17:40 UTC, Anillc commented on adapters/telegram/src/bot.ts
> +      return await this.file.file(`/${filePath}`)
这看上去需要在 cordis-axios 上进行一些修复

2023-03-01 05:30 UTC, shigma commented on adapters/telegram/src/bot.ts
> +      return await this.file.file(`/${filePath}`)
已更新

2023-03-01 16:28 UTC, Anillc approved these changes

2023-03-01 16:35 UTC, merged