fix: filename does not contain an extension
satorijs/satori pull request #84
Opened 2023-03-12 07:32 UTC by idanran

Fixes koishijs/koishi#1006

2023-03-12 07:36 UTC, Anillc commented on packages/axios/src/index.ts
> +    if (!name.includes('.')){
这个是不是还是不能解决你的问题，onebot 那边受到的图片名有 `.image` 后缀吧

2023-03-12 07:43 UTC, shigma commented on packages/axios/src/index.ts
> +    if (!name.includes('.')){
所以安妮觉得应该怎么办（

2023-03-12 07:43 UTC, idanran commented on packages/axios/src/index.ts
> +    if (!name.includes('.')){
```
async function appendAsset(bot: TelegramBot, form: FormData, element: segment): Promise<AssetType> {
  let assetType: AssetType
  const { filename, data, mime } = await bot.ctx.http.file(element.attrs.url)
  ...
  form.append(assetType, value, filename)
}
```
目前是没有使用 element.attrs.file，文件名从链接中匹配，所以也就没有 `.image` 后缀。
文件链接示例：`https://gchat.qpic.cn/gchatpic_new/2098923471/654259434-2772636126-02FC64EBBB991D951CDF49008EDAAB01/0?term=3&is_origin=0`

2023-03-12 07:45 UTC, Anillc commented on packages/axios/src/index.ts
> +    if (!name.includes('.')){
那就没问题了

2023-03-12 07:49 UTC, Anillc requested changes

2023-03-12 07:49 UTC, Anillc commented on packages/axios/src/index.ts
> +    let [_, name] = this.resolve(url).match(/.+\/([^/]*)(?=\?)/)
这个正则表达式有问题吧，只会匹配带有 `?` 的链接

2023-03-12 07:51 UTC, Anillc commented on packages/axios/src/index.ts
> +    let [_, name] = this.resolve(url).match(/.+\/([^/]*)(?=\?)/)
改成这样？`/.+\/([^/?]*)(?=\?)?/`

2023-03-12 08:08 UTC, idanran commented on packages/axios/src/index.ts
> +    let [_, name] = this.resolve(url).match(/.+\/([^/]*)(?=\?)/)
> 改成这样？`/.+\/([^/?]*)(?=\?)?/`

改好了。

```
'https://gchat.qpic.cn/gchatpic_new/2098923471/654259434-2772636126-02FC64EBBB991D951CDF49008EDAAB01/0'.match(/.+\/([^/?]*)(?=\?)?/)[1]

'https://gchat.qpic.cn/gchatpic_new/2098923471/654259434-2772636126-02FC64EBBB991D951CDF49008EDAAB01/0?term=3&is_origin=0'.match(/.+\/([^/?]*)(?=\?)?/)[1]
```
浏览器试了下 `/.+\/([^/?]*)(?=\?)?/`，与预期结果一致。

2023-03-12 08:09 UTC, Anillc approved these changes

2023-03-13 07:19 UTC, shigma approved these changes

2023-03-13 07:19 UTC, shigma commented on packages/axios/src/index.ts
> +    if (!name.includes('.')){
```suggestion
    if (!name.includes('.')) {
```

2023-03-13 07:21 UTC, merged